apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: exposecontroller
    context: ./home/jenkins/go/src/github.com/jenkins-x/exposecontroller
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/fsa-streamotion/exposecontroller:{{.VERSION}}'
  local: {}