apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: exposecontroller
    context: .
    docker:
      network: host
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/fsa-streamotion/exposecontroller:{{.VERSION}}'
  local: {}